# Generated by Django 4.2.6 on 2023-10-28 05:11


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_sale', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesales',
            name='store_ugo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storeSales', to='user.usergrouporganization', verbose_name='store'),
        ),
        migrations.AddField(
            model_name='invoicesales',
            name='wholesaler_ugo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesalerSales', to='user.usergrouporganization', verbose_name='wholesaler'),
        ),
    ]
