# Generated by Django 4.2.6 on 2023-10-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usergrouporganization', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('is_read_by_admin', models.BooleanField(db_index=True, default=False, verbose_name='is read by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.complaintresponse', verbose_name='response')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.complaintstatus', verbose_name='status')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_id', to='user.usergrouporganization', verbose_name='store id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user.usergrouporganization', verbose_name='user')),
            ],
        ),
    ]
