# Generated by Django 4.2.6 on 2023-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouporganization',
            name='ugo_code',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='code'),
        ),
    ]
