# Generated by Django 4.2.6 on 2023-10-25 11:17

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usergrouporganization_ugo_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.MyUserManager()),
            ],
        ),
    ]
