# Generated by Django 4.2.6 on 2023-10-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=15, verbose_name='driver')),
                ('full_weight', models.FloatField(verbose_name='full weight')),
                ('empty_weight', models.FloatField(verbose_name='empty name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'invoice entry',
                'verbose_name_plural': 'invoice entries',
            },
        ),
        migrations.CreateModel(
            name='InvoiceEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='weight')),
                ('invoice_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice_entry.invoiceentry', verbose_name='invoice_entry_id')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='product slug')),
            ],
            options={
                'verbose_name': 'invoice entry item',
                'verbose_name_plural': 'invoice entry items',
            },
        ),
    ]
