# Generated by Django 4.2.6 on 2023-10-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_entry', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceentry',
            name='wholesaler_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usergrouporganization', verbose_name='wholesaler'),
        ),
    ]
